kind: MessagingServer
apiVersion: integration.ibm.com/v1beta1
metadata:
  name: sample-messagingserver
spec:
  queueManager:
    name: MSGSERVERQM
    storage:
      defaultClass: ibmc-vpc-block-10iops-tier
    availability:
      type: NativeHA
